### ISSUE TITLE
Use the same syllable time offset for repeated vocal lines by linking lines together

### ISSUE THREAD

**Issue by PlaylistsTrance** [Juna-Idler/RhythmiKaRuTTE_Spectro#3]
This might be difficult to implement, but I've got an idea that may be useful for everyone. For songs that repeat lines (such as the lines that are present in every chorus), producers often use the same vocal recording. It would be great if users could 'link' duplicate lines, such that changing the position of a syllable marker in one line, changes it by the same offset from a line's starting timestamp in all linked lines.
This would make the LRC file more consistent, and it will also be faster as you don't have to time the syllables for the other linked lines, only the start timestamp.

Hopefully you understand what I mean. I also understand you probably don't want to implement this, but it's also a reminder for myself that I would like this feature.

**Comment by Juna-Idler** [comment]
As you can imagine, this isn't motivating at all.
1. Difficult to implement.
2. The same lyrics line does not always have the same timing.
3. I don't want to add useful functions for the lukewarm work of "sound phrase copy and paste".


Well, if there's one possibility, maybe it's time to make up a new karaoke time format that I used to think about.
```
[00:00.00]abc [0.50]def [.50]ghi[50]
[00:02.00]jkl [0.25]mno [1.25]pqr[1.]
```
Except for the beginning of the line, describe the relative time from the previous time.
Well, I didn't pay much attention to the karaoke format, so I stopped thinking about it.



ご想像の通りこれは全くやる気にならない。
1. 実装が難しい。
2. 同じ歌詞行が同じタイミングとは限らない。
3. サウンドフレーズコピペという手抜きに対する便利機能なんてつけたくない。


まあ一つだけ可能性があるなら、昔考えてた新カラオケタイムフォーマットをでっち上げるときかな？
```
[00:00.00]abc [0.50]def [.50]ghi[50]
[00:02.00]jkl [0.25]mno [1.25]pqr[1.]
```
行頭以外は直前の時間からの相対時間を記述する。
まあカラオケフォーマットにそんなに思い入れもないので、思い付き程度で止まってるけど。

**Comment by PlaylistsTrance** [comment]
Yes, I understand. You're right that they don't always have the same timing, but after the user changed the first occurrence of a line, and realizes it doesn't match up in a different occurrence, they would just 'unlink' them.
I think your offset idea would be great! The users could just copy-paste the first occurrence's timing to all other occurrences in TextEdit, right? And on Download it would use regular timestamps again. That's already very close to my suggestion, and I would love to see that. It seems much easier to implement as well.

**Comment by Juna-Idler** [comment]
No, I won't do it.
This is just an external format, and absolute time is easier when handling it inside the program.
There is no point in converting if the final output is in absolute time. (I'm not enthusiastic about duplicating lines)

いや、やらないよ？
これはあくまで外部フォーマットで、プログラム内部で扱うなら絶対時間の方が楽だし。
最終的に絶対時間で出力するなら変換する意味がない。（私は行の複製に乗り気ではない）
