### ISSUE TITLE
Don't include untimed markers in Output

### ISSUE THREAD

**Issue by PlaylistsTrance** [Juna-Idler/RhythmiKaRuTTE_Spectro#5]
Could you change the output page to exclude timestamps ending on `;np` (like `[00:00.00;pn]`)?

**Comment by Juna-Idler** [comment]
On the output page (displayed with the button in the lower right corner of TextEdit), that weird option should have been turned off, but isn't it?

アウトプットページ（TextEditの右下隅のボタンで表示）でなら、その変なオプションは消してるはずだけど、そうじゃなくて？

**Comment by PlaylistsTrance** [comment]
I tried a few different timestamps, these timestamps are ignored as expected: `[99:99.99;np]`, `[99:59.99;np]`, they don't show up in Output. However, other timestamps that end with `;np` become regular timestamps. I didn't realise this. I don't think this is a problem anymore, if I just make sure to use the two untimed examples that work.

**Comment by Juna-Idler** [comment]
I noticed when I was playing with Output for a while.
There was a stamp that didn't disappear when it was Line Head, and when I looked it up, I skipped the check.

ちょっとOutputを弄っていたら気が付いた。
Line Headだと消えてないスタンプがあって、調べたら大分チェックをさぼってた。

**Comment by PlaylistsTrance** [comment]
Perfect, that has solved it!
