### ISSUE TITLE
Go to TagStamp selected timestamp when going from TagStamp to TagPoint

### ISSUE THREAD

**Issue by PlaylistsTrance** [Juna-Idler/RhythmiKaRuTTE_Spectro#7]
Currently when I'm in TagStamp sometimes I discover a TagPoint placement is wrong or missing. It would be nice if it automatically used the selected timestamp from the TagStamp window when going from TagStamp to TagPoint so you're close to the part that needs correcting. A bit off-topic, but would it also be possible to have line numbers in front of lines in TextEdit?

**Comment by Juna-Idler** [comment]
If it's just the position of the line, it looks like this?

行の位置だけならこんな感じ？

**Comment by Juna-Idler** [comment]
Line numbers seem possible, but I'm not sure if it's easy.

行番号は出来そうだけど、簡単にできるかどうかは分からない。

**Comment by PlaylistsTrance** [comment]
> If it's just the position of the line, it looks like this?

Yes, that works perfectly!

> Line numbers seem possible, but I'm not sure if it's easy.

Alright, thank you for looking into it at least. It would just be a quality of life feature to find the particular lines I was timing but where I discovered something was wrong in the text, or when I want to add/remove a newline. I know you're meant to do that before you start timing, though.
